import os

IGNORE_HIDDEN = os.environ.get('IGNORE_HIDDEN') or True
DOMAINS = os.environ.get('DOMAINS', '').split(',') 

RCMS_REDSALE_MAIN_ENDPOINT_PRIVATE = os.environ.get('RCMS_REDSALE_MAIN_ENDPOINT_PRIVATE')
RCMS_REDSALE_MAIN_ENDPOINT = os.environ.get('RCMS_REDSALE_MAIN_ENDPOINT')
RCMS_BASIC_CREDENTIALS = os.environ.get('RCMS_BASIC_CREDENTIALS') 

MINIO_ENDPOINT_PRIVATE = os.environ.get('MINIO_ENDPOINT_RIVATE') 
MINIO_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY') 
MINIO_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY') 
MINIO_RESOURCES_BUCKET = os.environ.get('MINIO_RESOURCES_BUCKET') 
MINIO_CACHE_BUCKET = os.environ.get('MINIO_CACHE_BUCKET') 